"""empty message

Revision ID: 074d4653bc43
Revises: 
Create Date: 2017-04-20 12:02:52.628249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074d4653bc43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(length=2000), nullable=True),
    sa.Column('cover_picture', sa.String(length=2000), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('emails', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('attending', sa.Integer(), nullable=True),
    sa.Column('noreply', sa.Integer(), nullable=True),
    sa.Column('declined', sa.Integer(), nullable=True),
    sa.Column('maybe', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('cover_picture', sa.String(), nullable=True),
    sa.Column('time_from_now', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('venue_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('venues')
    # ### end Alembic commands ###
