"""empty message

Revision ID: b06bf7dc7fcb
Revises: 
Create Date: 2017-04-17 22:54:28.952008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06bf7dc7fcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(length=2000), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('cover_picture', sa.String(length=2000), nullable=True),
    sa.Column('emails', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues')
    # ### end Alembic commands ###
