"""empty message

Revision ID: cf84eadb6ece
Revises: 7c50c9d84f90
Create Date: 2017-04-18 03:57:22.011371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf84eadb6ece'
down_revision = '7c50c9d84f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('venue_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'events', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'venue_id')
    # ### end Alembic commands ###
